services:
  db:
    image: postgres:16
    container_name: db_app
    command: -p 5432
    env_file:
      - .env-non-dev

  app:
    build: .
    env_file:
      - .env-non-dev
    container_name: fastapi_app
    command: ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
    ports:
      - "8000:8000"
    depends_on:
      - db
